#!/bin/sh
# Openshift WildFly runtime configuration update

source ${JBOSS_HOME}/bin/launch/openshift-config-modules.sh
source $JBOSS_HOME/bin/launch/logging.sh
source $JBOSS_HOME/bin/launch/configure-modules.sh

configureConfigModules

exec_cli_scripts "${CLI_SCRIPT_FILE}"

if [ "${SCRIPT_DEBUG}" = "true" ] ; then
  echo "CLI Script used to configure the server: ${CLI_SCRIPT_FILE_FOR_EMBEDDED}"
  echo "CLI Script generated by launch: ${CLI_SCRIPT_FILE}"
  echo "CLI Script property file: ${CLI_SCRIPT_PROPERTY_FILE}"
  echo "CLI Script error file: ${CLI_SCRIPT_ERROR_FILE}"
fi